ALTER TABLE personajes
ADD COLUMN IF NOT EXISTS salvacion_fuerza INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS salvacion_destreza INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS salvacion_constitucion INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS salvacion_inteligencia INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS salvacion_sabiduria INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS salvacion_carisma INTEGER NOT NULL DEFAULT 0;
