const { Router } = require('express')

const { adminRouter } = require('./admin.routes')
const { authRouter } = require('./auth.routes')
const { campaignsRouter } = require('./campaigns.routes')
const { charactersRouter } = require('./characters.routes')
const { classesRouter } = require('./classes.routes')
const { commentsRouter } = require('./comments.routes')
const { crudRouter } = require('./crud.routes')
const { favoritesRouter } = require('./favorites.routes')
const { featsRouter } = require('./feats.routes')
const { healthRouter } = require('./health.routes')
const { mediaRouter } = require('./media.routes')
const { notificationsRouter } = require('./notifications.routes')
const { objectsRouter } = require('./objects.routes')
const { placesRouter } = require('./places.routes')
const { powersRouter } = require('./powers.routes')
const { resourcesRouter } = require('./resources.routes')
const { searchRouter } = require('./search.routes')
const { settingsRouter } = require('./settings.routes')
const { spellsRouter } = require('./spells.routes')
const { usersRouter } = require('./users.routes')
const { wikiRouter } = require('./wiki.routes')

const apiRouter = Router()

apiRouter.use('/health', healthRouter)
apiRouter.use('/auth', authRouter)
apiRouter.use('/admin', adminRouter)
apiRouter.use('/users', usersRouter)
apiRouter.use('/settings', settingsRouter)
apiRouter.use('/campaigns', campaignsRouter)
apiRouter.use('/characters', charactersRouter)
apiRouter.use('/classes', classesRouter)
apiRouter.use('/comments', commentsRouter)
apiRouter.use('/objects', objectsRouter)
apiRouter.use('/places', placesRouter)
apiRouter.use('/powers', powersRouter)
apiRouter.use('/resources', resourcesRouter)
apiRouter.use('/search', searchRouter)
apiRouter.use('/notifications', notificationsRouter)
apiRouter.use('/favorites', favoritesRouter)
apiRouter.use('/feats', featsRouter)
apiRouter.use('/spells', spellsRouter)
apiRouter.use('/media', mediaRouter)
apiRouter.use('/crud', crudRouter)
apiRouter.use('/wiki', wikiRouter)

module.exports = {
  apiRouter,
}
